language: java
jdk:
  - oraclejdk8
services:
  #- redis
sudo: required
cache:
  directories:
    - $HOME/.m2
install: true
script: mvn install
after_success:
  - mvn cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)
